name: Simple Check

on:
  push:
    branches:
      - main

jobs:
  check-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Push berhasil!"
